### ISSUE TITLE
Integrating with ng-packagr

### ISSUE THREAD

**Issue by Geoffrey0** [brechtbilliet/ngxReactiveToolkit#1]
When I use the Changes or Destroy decorator together with ng-packagr. It throws me the following error : 

BUILD ERROR
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at ClassRewriter.shouldLower (../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/decorator-annotator.js:34:106)
    at ../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/decorator-annotator.js:71:68
    at Array.filter (native)
    at ClassRewriter.decoratorsToLower (../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/decorator-annotator.js:71:33)
    at ClassRewriter.gatherMethodOrProperty (../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/decorator-annotator.js:156:31)
    at ClassRewriter.maybeProcess (../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/decorator-annotator.js:183:22)
    at ClassRewriter.Rewriter.visit (../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/rewriter.js:52:19)
    at ../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/tsickle/build/src/decorator-annotator.js:92:19
    at visitEachNode (../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/typescript/lib/typescript.js:14785:30)
    at Object.forEachChild (../node_modules/ng-packagr/node_modules/@angular/tsc-wrapped/node_modules/typescript/lib/typescript.js:15032:21)

It seems like an error with tsickle together with the decorators. 

I find both of these decorators really helpful and I would like to be able to use them in our component library.

**Comment by brechtbilliet** [comment]
I'm aware of this problem... Turns out AOT will filter away the lifecycle methods (like ngOnDestroy) if the class doesn't contain them (so if they are added by decorators). The solution to this is to add an empty ngOnDestroy function.
I'm thinking about a better solution for this.
